include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - prefer_final_fields
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - prefer_is_empty
    - prefer_is_not_empty
