name: baothe_vn
description: "Công cụ quản lý thẻ tín dụng và chi tiêu cá nhân thông minh, tích hợp AI để phân tích và dự đoán chi tiêu, giúp người dùng kiểm soát tài chính hiệu quả."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  
  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  
  # State Management & Routing
  flutter_riverpod:
  go_router:
  
  # UI & Utils
  google_fonts:
  intl:
  cached_network_image:
  font_awesome_flutter:
  url_launcher:
  shared_preferences:
  
  # New dependencies
  uuid:
  fl_chart: ^0.70.0 # Older version for compatibility
  flutter_local_notifications:
  timezone:
  flutter_animate:
  smooth_page_indicator: ^1.2.0 # Older version for compatibility
  table_calendar:
  google_sign_in: 6.3.0
  sign_in_with_apple:
  # AI & Networking
  http:
  google_generative_ai:
  flutter_markdown:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_lint:
  custom_lint:
  flutter_launcher_icons:
  flutter_native_splash:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_app.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo/logo_app.png"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/design/web/
    - assets/design/mobile/
