// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6xqm7DgLKjuDL9nEazhBCeXiUV5bufZo',
    appId: '1:1008690396766:web:ba8ff9a07f258103f07ecf',
    messagingSenderId: '1008690396766',
    projectId: 'baothevn-790c6',
    authDomain: 'baothevn-790c6.firebaseapp.com',
    storageBucket: 'baothevn-790c6.firebasestorage.app',
    measurementId: 'G-FKFP5CK410',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aCqPhoKh9nC5xErj_aRQyKVD_bukCP0',
    appId: '1:1008690396766:android:8165552ea9fd6b84f07ecf',
    messagingSenderId: '1008690396766',
    projectId: 'baothevn-790c6',
    storageBucket: 'baothevn-790c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlnz6ZgeOZ1JmKO4deGuIQDuoCzox3Dw',
    appId: '1:1008690396766:ios:6e16f69b768a83dbf07ecf',
    messagingSenderId: '1008690396766',
    projectId: 'baothevn-790c6',
    storageBucket: 'baothevn-790c6.firebasestorage.app',
    iosBundleId: 'com.example.baotheVn',
  );
}
